# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Run-npm-on-OS:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x]

    steps:
    # Check out the latest code from repository
    - name: Check out the latest code from repository.
    - uses: actions/checkout@v4

    # Setup Node.js environment
    - name: Setup Node.js ${{ matrix.node-version }} on Windows
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install project dependencies
    - name: Install project dependencies
    - run: npm ci
    - run: npm run build --if-present

    # Run test suite
    - name: Run test suite
    - run: npm test